const quotes = [

"Loving you feels like finding shade on the hottest day.",
"Your presence turns ordinary moments into quiet magic.",
"Some people arrive softly and become your safest place.",
"With you, silence sounds beautiful.",
"Love is how your name feels at home in my mouth.",
"You are the calm my restless heart was looking for.",
"In your eyes, even chaos feels gentle.",
"Home was never a place until I met you.",
"The world softens whenever you are near.",
"Loving you feels like watching sunrise without needing words.",
"You are the kind of peace people spend years searching for.",
"My favorite part of every day is knowing you are in it.",
"You make even waiting feel worthwhile.",
"Some love stories are loud. Ours is beautifully quiet.",
"Even the smallest moments with you feel infinite.",
"Your smile lingers longer than any memory should.",
"Love is the way your existence makes mine lighter.",
"You feel like warmth after a long winter.",
"I never knew comfort could have a face.",
"If peace had a heartbeat, it would sound like you.",
"Every glance from you rewrites my entire day.",
"Love is your hand finding mine without looking.",
"You are the pause my soul needed.",
"The gentlest things often stay the longest.",
"You make forever feel simple.",
"Real love grows, even when life gets difficult.",
"Love is not arrival; it is choosing the road together.",
"The strongest hearts are built, not found.",
"Growing with someone is the rarest kind of intimacy.",
"Love matures where patience is planted.",
"Becoming better together is love's quiet masterpiece.",
"The best love teaches without demanding.",
"Some journeys matter because of who walks beside you.",
"Love is learning each other through every season.",
"Growth is love refusing to stay shallow.",
"Real connection survives change and becomes deeper because of it.",
"Love is choosing understanding before judgment.",
"Two people growing separately can still bloom together.",
"Every challenge faced together becomes part of the foundation.",
"Love evolves when both people stay curious.",
"The right love stretches you toward your best self.",
"Not all growth is loud; some happens in quiet loyalty.",
"Love is built in ordinary acts repeated consistently.",
"The deepest bonds are shaped by weathering storms.",
"Love means becoming, not just belonging.",
"A lasting love keeps making room for who you become.",
"Growth asks for courage; love makes courage easier.",
"Love becomes timeless when it keeps transforming.",
"We are meant to expand, not remain who we were.",
"The truest love grows roots while reaching for light.",
"You're my favorite distraction.",
"If I were a cat, I'd spend all nine lives annoying you.",
"Loving you should count as cardio.",
"You're proof my standards were secretly waiting for you.",
"I smile at my phone because of you. It's embarrassing.",
"You stole my heart. Keep it, it matches you.",
"I like you more than sleeping in, and that's serious.",
"You're my favorite notification.",
"If kisses were currency, I'd be bankrupt around you.",
"You're suspiciously good at making me blush.",
"My heart has terrible taste. It picked you.",
"You're the plot twist I didn't know I wanted.",
"I'd share my fries with you. Think about that.",
"Loving you is my least productive habit.",
"You make my brain forget how to act normal.",
"You're the reason my screen time is concerning.",
"I'm not clingy, I'm just emotionally Wi-Fi connected to you.",
"If cute were illegal, you'd be serving life.",
"You're annoyingly lovable.",
"I blame you for this smile.",
"Even autocorrect knows your name now.",
"I'd lose every argument on purpose if it meant your smile.",
"You make awkward look adorable.",
"My heart reacts to you like a puppy hearing treats.",
"Honestly, you're kind of my favorite problem.",
"Some souls recognize each other before words are spoken.",
"Love is memory reaching beyond time.",
"The deepest connections feel ancient and new at once.",
"Some people arrive like echoes from another lifetime.",
"Love is what remains when everything temporary fades.",
"Certain hearts are written into each other's becoming.",
"Time measures life, but love measures meaning.",
"To truly love is to witness eternity in another person.",
"Some bonds outlive explanation.",
"Love is the only language silence never mistranslates.",
"What is real in love cannot be rushed or erased.",
"Souls remember what minds forget.",
"Love leaves fingerprints on time itself.",
"The truest love reshapes your understanding of existence.",
"Some connections are too profound for logic alone.",
"Love survives because truth does.",
"Eternity often arrives disguised as a moment.",
"We are remembered most by how deeply we loved.",
"Love is life recognizing itself in another form.",
"The heart understands distances time cannot measure.",
"What is destined does not force itself; it remains.",
"Love is the art of staying open to mystery.",
"Some people become part of your inner architecture forever.",
"The deepest love asks for presence, not possession.",
"What is timeless never needs proof.",

];